from __future__ import annotations
from typing import Protocol, AsyncIterator, runtime_checkable, Dict, Any

@runtime_checkable
class LLMRouter(Protocol):
    def name(self) -> str: ...
    async def health(self) -> dict: ...
    async def complete(self, req: Dict[str, Any]) -> Dict[str, Any]: ...
    async def stream(self, req: Dict[str, Any]) -> AsyncIterator[Dict[str, Any]]: ...
